//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bazaUlazniceEntities : DbContext
    {
        public bazaUlazniceEntities()
            : base("name=bazaUlazniceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Burza> Burza { get; set; }
        public virtual DbSet<Dogadjaj> Dogadjaj { get; set; }
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<Karta> Karta { get; set; }
        public virtual DbSet<Kazaliste> Kazaliste { get; set; }
        public virtual DbSet<Klub> Klub { get; set; }
        public virtual DbSet<KupljeneKarte> KupljeneKarte { get; set; }
        public virtual DbSet<Lokacija> Lokacija { get; set; }
        public virtual DbSet<VrstaKarte> VrstaKarte { get; set; }
        public virtual DbSet<Izvodjac> Izvodjac { get; set; }
        public virtual DbSet<Koncert> Koncert { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
    }
}
