//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogadjaj
    {
        public Dogadjaj()
        {
            this.Karta = new HashSet<Karta>();
            this.Kazaliste = new HashSet<Kazaliste>();
            this.Klub = new HashSet<Klub>();
            this.Koncert = new HashSet<Koncert>();
        }
    
        public int Id { get; set; }
        public string naziv { get; set; }
        public System.DateTime datum { get; set; }
        public int IdLokacija { get; set; }
        public int brojmjesta { get; set; }
        public byte[] plakat { get; set; }
    
        public virtual Lokacija Lokacija { get; set; }
        public virtual ICollection<Karta> Karta { get; set; }
        public virtual ICollection<Kazaliste> Kazaliste { get; set; }
        public virtual ICollection<Klub> Klub { get; set; }
        public virtual ICollection<Koncert> Koncert { get; set; }
    }
}
