//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grad
    {
        public Grad()
        {
            this.Lokacija = new HashSet<Lokacija>();
        }
    
        public int Id { get; set; }
        public string imegrad { get; set; }
    
        public virtual ICollection<Lokacija> Lokacija { get; set; }
    }
}
