//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public Karta()
        {
            this.KupljeneKarte = new HashSet<KupljeneKarte>();
        }
    
        public int Id { get; set; }
        public int IdVrstakarte { get; set; }
        public decimal cijena { get; set; }
        public int IdDogadjaj { get; set; }
        public string zastitnikod { get; set; }
        public byte[] QR_KOD { get; set; }
        public Nullable<int> brojkarte { get; set; }
    
        public virtual Dogadjaj Dogadjaj { get; set; }
        public virtual VrstaKarte VrstaKarte { get; set; }
        public virtual ICollection<KupljeneKarte> KupljeneKarte { get; set; }
    }
}
