//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kazaliste
    {
        public int Id { get; set; }
        public int IdDogadjaj { get; set; }
    
        public virtual Dogadjaj Dogadjaj { get; set; }
    }
}
