//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KupljeneKarte
    {
        public KupljeneKarte()
        {
            this.Burza = new HashSet<Burza>();
        }
    
        public int Id { get; set; }
        public int IdKorisnik { get; set; }
        public int IdKarta { get; set; }
    
        public virtual ICollection<Burza> Burza { get; set; }
        public virtual Karta Karta { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
