//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokacija
    {
        public Lokacija()
        {
            this.Dogadjaj = new HashSet<Dogadjaj>();
        }
    
        public int Id { get; set; }
        public string adresa { get; set; }
        public string naziv { get; set; }
        public int IdGrad { get; set; }
    
        public virtual ICollection<Dogadjaj> Dogadjaj { get; set; }
        public virtual Grad Grad { get; set; }
    }
}
