//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VrstaKarte
    {
        public VrstaKarte()
        {
            this.CijenaKarte = new HashSet<CijenaKarte>();
        }
    
        public int Id { get; set; }
        public string imekategorije { get; set; }
        public int IdLokacija { get; set; }
    
        public virtual ICollection<CijenaKarte> CijenaKarte { get; set; }
        public virtual Lokacija Lokacija { get; set; }
    }
}
